[package]
name = "tokio-ngtcp2"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
shiguredo_ngtcp2 = { path = "../ngtcp2-rs" }
tokio = { version = "1.52", features = ["full"] }

[dev-dependencies]
rcgen = "0.14"
serial_test = "3.4"
shiguredo_http3.workspace = true
