[package]
name = "tokio-s2n-quic"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[[example]]
name = "tokio_s2n_quic_h3_server"
path = "examples/h3_server.rs"

[[example]]
name = "tokio_s2n_quic_h3_client"
path = "examples/h3_client.rs"

[[example]]
name = "tokio_s2n_quic_wt_echo_server"
path = "examples/wt_echo_server.rs"

[[example]]
name = "tokio_s2n_quic_wt_echo_client"
path = "examples/wt_echo_client.rs"

[dependencies]
bytes = "1.11"
s2n-quic = "1.80"
shiguredo_http3 = { path = "../.." }
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "sync"] }

[dev-dependencies]
rcgen = "0.14"
tokio = { version = "1.52", features = ["full", "test-util"] }
